import localFont from "next/font/local";
import "./globals.css";
import "./mostHave.css";


const body = localFont({
  src:  "./fonts/AktivGrotesk.ttf",
  variable: "--font-body",
 
});
const custom = localFont({
  src:  "./fonts/Galgo.otf",
  variable: "--font-custom",
 
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${custom.variable} ${body.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
